import fs from 'fs/promises';
import logger from './logger.js';

/**
 * Local-demo reasoning backend: same execute(prompt, { cwd }) contract as
 * CodexExecutor, but no OpenAI account needed. Selected in index.js when
 * MOCK_EXECUTOR=true. Replies are honest about being canned — they name the
 * files in the tenant directory so the pipeline (upload → AGENTS.md →
 * per-tenant cwd → persisted history) is still exercised end to end.
 */
export class MockExecutor {
  async execute(prompt, { cwd } = {}) {
    if (!cwd) {
      throw new Error('MockExecutor.execute requires a cwd (the tenant directory)');
    }

    const startTime = Date.now();
    const question = prompt.match(/User message:\n"""\n([\s\S]*?)\n"""/)?.[1].trim() ?? '';

    let files = [];
    try {
      files = (await fs.readdir(cwd)).filter((f) => f !== 'AGENTS.md');
    } catch {
      // Tenant directory may not exist yet on a brand-new chat.
    }

    const docSummary = files.length === 0
      ? 'Your document library is empty — upload files on the Documents page (admin key) and attach them to a chat.'
      : `I can see ${files.length} document${files.length === 1 ? '' : 's'} in your library: ${files.join(', ')}.`;

    const output = [
      `You asked: "${question}"`,
      '',
      docSummary,
      '',
      '*This is a demo reply — the app is running in local preview mode without an OpenAI key, ' +
      'so responses are generated by a built-in mock instead of a real AI. ' +
      'To get real AI answers, set OPENAI_API_KEY and MOCK_EXECUTOR=false, then restart.*'
    ].join('\n');

    logger.info('MockExecutor replied (demo mode, no AI call made)', { cwd });
    return { output, executionTime: Date.now() - startTime };
  }
}

export default MockExecutor;
