import path from 'path';
import fs from 'fs/promises';
import { dataDir } from './env.js';

/**
 * The ONLY module allowed to build tenant filesystem paths. Directory
 * isolation is the tenancy boundary: codex exec runs with cwd = tenantRoot,
 * so nothing outside this module may join paths into tenant storage.
 */

// Generated by the server, never uploadable (see sanitizeFilename).
export const AGENTS_FILENAME = 'AGENTS.md';

// Per-chat history files the agent can read on demand. Dot-prefixed so no
// upload can collide (sanitizeFilename rejects dotfile names) and AGENTS.md
// never lists it.
export const CHATS_DIRNAME = '.chats';

export function tenantRoot(tenantId) {
  const id = String(tenantId);
  // Tenant ids are server-generated UUIDs, but guard anyway: an id that
  // changes under path resolution is hostile input.
  const root = path.resolve(dataDir(), 'tenants', id);
  const base = path.resolve(dataDir(), 'tenants');
  if (path.dirname(root) !== base) {
    throw new Error(`Invalid tenant id: ${tenantId}`);
  }
  return root;
}

export async function ensureTenantRoot(tenantId) {
  const root = tenantRoot(tenantId);
  await fs.mkdir(root, { recursive: true });
  return root;
}

/**
 * Reduce an uploaded filename to a safe basename: strip any path components,
 * collapse disallowed characters, and refuse the reserved AGENTS.md name.
 */
export function sanitizeFilename(original) {
  const base = path.basename(String(original || ''))
    .replace(/[^\w.\- ]+/g, '_')
    .replace(/\s+/g, ' ')
    .trim();

  if (!base || base === '.' || base === '..' || base.startsWith('.')) {
    return 'document';
  }
  if (base.toLowerCase() === AGENTS_FILENAME.toLowerCase()) {
    return 'document.md';
  }
  return base;
}

/**
 * Absolute path of a chat's history file, plus the tenant-relative path the
 * prompt hands to the agent. Chat ids are server-generated UUIDs, but guard
 * against path tricks anyway, like tenantRoot does.
 */
export function chatHistoryPath(tenantId, chatId) {
  const dir = path.join(tenantRoot(tenantId), CHATS_DIRNAME);
  const resolved = path.resolve(dir, `${chatId}.json`);
  if (path.dirname(resolved) !== dir) {
    throw new Error(`Invalid chat id: ${chatId}`);
  }
  return { absolute: resolved, relative: path.join(CHATS_DIRNAME, `${chatId}.json`) };
}

export async function writeChatHistory(tenantId, chatId, messages) {
  const { absolute, relative } = chatHistoryPath(tenantId, chatId);
  await fs.mkdir(path.dirname(absolute), { recursive: true });
  await fs.writeFile(absolute, JSON.stringify(messages, null, 2));
  return relative;
}

export async function removeChatHistory(tenantId, chatId) {
  const { absolute } = chatHistoryPath(tenantId, chatId);
  await fs.rm(absolute, { force: true });
}

/**
 * Absolute path for a document inside the tenant's directory. Throws if the
 * resolved path escapes the tenant root — defense in depth on top of
 * sanitizeFilename.
 */
export function documentPath(tenantId, filename) {
  const root = tenantRoot(tenantId);
  const resolved = path.resolve(root, filename);
  if (resolved !== path.join(root, path.basename(resolved)) || path.dirname(resolved) !== root) {
    throw new Error(`Invalid document filename: ${filename}`);
  }
  return resolved;
}
